name: Github Actions
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: jiro4989/setup-nim-action@v1

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.nimble/pkgs
        key: ${{ runner.os }}-${{ hashFiles('~/.nimble/pkgs/') }}
    
    - name: Install dependencies
      run: nimble install -y
    
    - name: Run tests
      run: testament pattern "tests/*.nim"